baseURL = "https://liuhack.github.io"
languageCode = "en-us"
title = "LiUhack"
theme = "hugo-theme-nix"
Paginate = 100

[menu]
  [[menu.header]]
    name = "writeups"
    weight = 0
    url = "/writeups"

[params]
  Name = "LiUhack"
  HeaderUsername = "LiUhack"
  HeaderHostname = "LiUhack.se"
  About = "LiUhack is a [CTF](https://en.wikipedia.org/wiki/Capture_the_flag#Computer_security) team which members are students at [Link√∂ping University](https://liu.se/). If you are interested to join us, feel free to send an email to us or contact us on our IRC channel [#liuhack on freenode](http://webchat.freenode.net?channels=%23liuhack&uio=d4)."
  ProfilePicture = "https://i.imgur.com/CZh5lbk.jpg"

TwitterID = "liuhackse"
GithubID = "liuhack"
Email = "liuhack@pm.me"
